ASPNET-CRUD-MVC/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ASPNET_CRUD_MVC.Models;
using ASPNET_CRUD_MVC.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASPNET_CRUD_MVC.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {
        private readonly IContactRepository _repository;
        public ContactController(IContactRepository repository)
        {
            _repository = repository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            List<ContactModel> list = _repository.GetAll();
            return View(list);
        }

        public IActionResult CreateContact()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateContact(ContactModel contact)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repository.Add(contact);
                    TempData["SucessMessage"] = "Contact was stored successfully";
                    return RedirectToAction("Index");
                }


                return View(contact);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"We have a problem during process to create a contact. Details {ex.Message}";
                return RedirectToAction("Index");
            }

        }

        public IActionResult EditContact(int id)
        {
            ContactModel model = _repository.GetById(id);
            return View(model);
        }


        [HttpPost]
        public IActionResult EditContact(ContactModel contact)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _repository.Update(contact);
                    TempData["SucessMessage"] = "Contact was updated successfully";
                    return RedirectToAction("Index");
                }


                return View(contact);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"We have a problem during process to update a contact. Details {ex.Message}";
                return RedirectToAction("Index");
            }

        }



        public IActionResult ConfirmToDeleteContact(int id)
        {
            ContactModel model = _repository.GetById(id);
            return View(model);
        }

        public IActionResult DeleteContact(int id)
        {
            try
            {
                bool deleted = _repository.Delete(id);
                if (deleted)
                {
                    TempData["SucessMessage"] = "Contact was deleted successfully";
                }
                else
                {
                    TempData["ErrorMessage"] = "We have a problem during process to delete a contact";
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"We have a problem during process to delete a contact. Details {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPNET-CRUD-MVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using ASPNET_CRUD_MVC.Models;
using ASPNET_CRUD_MVC.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ASPNET_CRUD_MVC.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly ILoginRepository _repository;

        public LoginController(ILoginRepository repository)
        {
            _repository = repository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel loginModel, string returnUrl = null)
        {
            UserModel userDb = _repository.Login(loginModel);
            if (userDb != null)
            {

                List<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, userDb.Id.ToString()),
                    new Claim(ClaimTypes.Name, userDb.UserName),
                };

                ClaimsIdentity identity = new ClaimsIdentity(claims, "Identity.Login");
                ClaimsPrincipal mainUser = new ClaimsPrincipal(new[] { identity });

                await HttpContext.SignInAsync(mainUser, new AuthenticationProperties
                {
                    IsPersistent = false,
                    ExpiresUtc = DateTime.Now.AddHours(1),
                });

                if (returnUrl != null)
                {
                    return LocalRedirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }


            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await HttpContext.SignOutAsync();
                return RedirectToPage("/Home");
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

ASPNET-CRUD-MVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using ASPNET_CRUD_MVC.Models;
using ASPNET_CRUD_MVC.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASPNET_CRUD_MVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserRepository _repository;

        public UserController(IUserRepository repository)
        {
            _repository = repository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<UserModel> listUsers = _repository.GetAll();
            return View(listUsers);
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(UserModel userModel)
        {
            UserModel userDb = _repository.GetByUserName(userModel.UserName);
            if (userDb != null &&
                userDb.Name == userModel.Name && userDb.Password == userModel.Password)
            {

                TempData["SucessMessage"] = "User authenticate";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ErrorMessage"] = $"User not found or password wrong";
                return RedirectToAction("Index");
            }
        }

        public IActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateUser(UserModel userModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repository.Add(userModel);
                    TempData["SucessMessage"] = "User was stored successfully";
                    return RedirectToAction("Index");
                }


                return View(userModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"We have a problem during process to create a user. Details {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult EditUser(int id)
        {
            UserModel userModel = _repository.GetById(id);
            return View(userModel);
        }


        [HttpPost]
        public IActionResult EditUser(UserModel userModel)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _repository.Update(userModel);
                    TempData["SucessMessage"] = "User was updated successfully";
                    return RedirectToAction("Index");
                }


                return View(userModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"We have a problem during process to update a User. Details {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult ConfirmToDeleteUser(int id)
        {
            UserModel userModel = _repository.GetById(id);
            return View(userModel);
        }

        public IActionResult DeleteUser(int id)
        {
            try
            {
                bool deleted = _repository.Delete(id);
                if (deleted)
                {
                    TempData["SucessMessage"] = "Contact was deleted successfully";
                }
                else
                {
                    TempData["ErrorMessage"] = "We have a problem during process to delete a contact";
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"We have a problem during process to delete a contact. Details {ex.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ASPNET-CRUD-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contacts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    </ul>

                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                }
                else
                {
                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                }

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASPNET_CRUD_MVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>